name: merge-trackers

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write  # 必须有写入权限才能创建 release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install
        run: npm install
      - name: Run Node.js script
        run: node index.js

      - name: 获取新版本号
        run: |
          # 尝试从 package.json 中获取版本号
          VERSION=$(date +%Y%m%d)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version:${VERSION}"
          echo "New version GITHUB_ENV:${GITHUB_ENV}"
        
      - name: 创建Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./MergeTrackers.txt
            ./MergeTrackers_Deduplicated.txt

